### ISSUE TITLE
你好，请问能够正确画出预测框吗？

### ISSUE THREAD

**Issue by xo-jiang** [qbbbbbb/ZYNQ_YOLOv3-tiny#2]
你好，请问能够正确画出预测框吗？我复现出来的误差很大，如果你能绘制出来那说明我的操作哪里有问题。如果你有时间回答这个问题，那非常感谢！

**Comment by qbbbbbb** [comment]
可以正确画出的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月17日(周四) 中午11:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qbbbbbb/ZYNQ_YOLOv3-tiny] 你好，请问能够正确画出预测框吗？ (Issue #2)




 
你好，请问能够正确画出预测框吗？我复现出来的误差很大，如果你能绘制出来那说明我的操作哪里有问题。如果你有时间回答这个问题，那非常感谢！

**Comment by xo-jiang** [comment]
非常感谢，我还想知道您用ZYNQ推理误差count计数是多少呀？

**Comment by qbbbbbb** [comment]
不好意思，这个项目已经好久之前的，具体细节已经记不太清楚



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月17日(周四) 中午11:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qbbbbbb/ZYNQ_YOLOv3-tiny] 你好，请问能够正确画出预测框吗？ (Issue #2)




 
非常感谢，我还想知道您用ZYNQ推理误差count计数是多少呀？

**Comment by xo-jiang** [comment]
好的，知道能预测出正确的框就行，我自己排查一下问题，非常感谢。
